# Generated by Django 4.1.7 on 2023-03-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='ecommerce/static/img/%Y/%m'),
        ),
    ]
