# Generated by Django 4.1.7 on 2023-04-09 10:54

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=100, verbose_name=ecommerce.models.Category),
        ),
    ]
